#!/bin/bash
#demonstrating variables in bash

STR="Welome to the world of shell"
echo $STR
echo 
echo "Env variable: $PATH"
echo 
echo "Env variable: $SHELL"
echo

n=10
function add {
          local n=20
          local m=30
          n=`expr $n + $m`
          echo "local variable fun n: $n"
}

add
echo "Global variable n: $n"

#########################################################################

PASSING VARIABLES IN THE FUNCTIONS

#########################################################################

#!/bin/bash
#demonstrating variables in bash

STR="Welome to the world of shell"
echo $STR
echo 
echo "Env variable: $PATH"
echo 
echo "Env variable: $SHELL"
echo

n=10
add() 
{
          n=`expr $1 + $2`
          echo "local variable fun n: $n"
}


echo "Global variable n: $n"
add 3 6
#############################################################################
export1.sh

#!/bin/bash
#Demonstrating export built-in function
var1=Hello
var2=Welcome
echo "your name please"
read name
echo "$var1 $name,$var2!"
export name
bash export2.sh
echo "value of name after exporting: $name"

________________________________________________
export2.sh

#!/bin/bash
echo "value of exported variable: $name"
name="saipavan"

wen we pass this export2.sh in the above export1.sh the variable is overwritten with the value in the export1.sh
######################################################

